name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 7
          days-before-close: 30
          stale-issue-label: 'status: stale'
          only-labels: 'status: waiting'
    
- name: Download a Build Artifact
  uses: actions/download-artifact@v2.1.1
  with:
    # Artifact name
    name: # optional
    # Destination path
    path: # optional
